# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b368c067173949af9190846aea4a3f23896bb8b46ce7ccf898fa7d6767a7a80853ce2512d324022501f756beb240202dbf32a803a6678acfd3ccff4ef0ca2fd

test:
  secret_key_base: 7f34715817c18b812010d8f61ae9d3e9d145411083fa75006e7cca6213439ef637c5b39467ed193d873f6861b16d6acc150bf0a1470f4089ceb31e61e02de791

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
